version: '3.8'

services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ../human_eval_tool/client/build:/usr/share/nginx/html
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/nginx/ssl
        network_mode: host
        # ports:
        #     - "80:80"
        #     - "443:443"
        #     - "8080:8080"
        # extra_hosts:
        #     - "host.docker.internal:host-gateway"



    
    # client:
    #     build: 
    #         context: ../human_eval_tool/client/
    #         dockerfile: deploy/Dockerfile
    #     container_name: client
    #     restart: unless-stopped
    #     volumes:
    #         - ../human_eval_tool/client:/usr/app
    #         - /usr/app/node_modules
    #     networks:
    #         my-network:
    #             aliases:
    #                 - client

