version: '3.1'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    extra_hosts:
            - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - "../data/mongo/:/data/db"
      - "../data/mongo/logs:/var/log/mongodb"
    
  mongo-express:
    links:
       - mongodb:mongo
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=3024-night
      - ME_CONFIG_BASICAUTH=true
    env_file:
      - .env
    depends_on:
      - mongodb
